name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:

  publish-crate:
    runs-on: ubuntu-20.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev
    - name: Publish Crate
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
      run: cargo publish
